### ISSUE TITLE
Duplicated use of category menu causes fatal erroru

### ISSUE THREAD

**Issue by Jimmi08** [Moc/cookbook#19]
## Bug Description
Fatal error: Cannot declare class cookbook_categoriesmenu, because the name is already in use in  ***\cookbook\cookbook_categories_menu.php on line 21

## How to Reproduce
1.  Add the category menu 2x on the same layout

Could you add a check if class already exists? 

 Thanks

**Comment by Moc** [comment]
I'll add it. 

Not sure why you would want two of the same menus on the same page though...

**Comment by Jimmi08** [comment]
You never know - in my case I just tested sidebar with 3 different menu areas  (see core bootstrap5 theme, it uses 2) and ended with this error.  In real life it should be never used, but if anybody do similar mistake (and it is very easy to do with the way how you are adding menus in menu manager), there will be no error. 
Just detail to avoid future complications.
