### ISSUE TITLE
Status 

### ISSUE THREAD

**Issue by ericc-dream** [Moc/cookbook#32]
Hi Moc 

I see that you said " NOT READY FOR RELEASE YET!! " 
Can you describe what is missing ? 
I'm using e107, and I love to publish some recipe. 
Actually, I'm doing it in a dedicated section of the forum but having a plugin for that can be interesting 

Is it "usable" ? even a little bit ?

Best regards

**Comment by Moc** [comment]
Hi, 

Thank you for your interest. There are a couple of features that I still need to finish up (although most of it is already done) before it's ready for an official release. See https://github.com/Moc/cookbook/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0

Having said that, I think the plugin is already quite usable. I would definitely appreciate getting some feedback, so if you'd like to try it, please do! I probably won't be making any major adjustments, so upgrading to the official release should not be a major issue (no promises though!).

**Comment by ericc-dream** [comment]
OK, thanks 
I cloned your repo, but I need some guidance 
I have a professional experience of git , and I'm not sure what is the process here 
At work, each one is creating his own "branch" (and some time several if they works on several project at the same time) like "wip/ericc/<something>", do them stuff, test and correct, then rebase and do a "merge request" with a reviewer 
When the reviewer approve, the merge is done into the master. 
How is it working with github ? I don't know the term "pull request" ? is it the same as a "merge request" ?

**Comment by ericc-dream** [comment]
"Github Desktop" is a Windows application, I'm working exclusively on Linux ... and I think that I don't need a graphical interface to manage my git commands. 
I do everything from the command line and it's faster 

I will read the docs 
Thanks

**Comment by ericc-dream** [comment]
Hi 

I have done the translation now. 
Now I try to commit my change and I can't ! 

At first I believed that it was because I had cloned with https ... so I reconfigure everything, create a rsa key , export the public to my profile and cloned with ssh 
Worked well 
Again, I created a local branch (wip/ericc/french) , added the folder and files to it , done the commit message, but when I try to push 

> ericc@webserver2:~/www/ericc/e107_plugins/cookbook$ git push --set-upstream origin wip/ericc/french
ERROR: Permission to Moc/cookbook.git denied to ericc-dream.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

Do you have to allow me to push to your repo ? 
most probably ! 
Or do I have to do request somehow ?

**Comment by Moc** [comment]
So normally the process is to fork my repository to your own account. This hasn't happened as far as I can see, as you don't have any repositories: https://github.com/ericc-dream?tab=repositories

Then you commit your changes to your own repository, and then submit a pull request as instructed here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by ericc-dream** [comment]
Ok, will do it
Sorry but this is the first time that I'm using github ... at least the
"public" version
We use it at work and the process is totally different

**Comment by ericc-dream** [comment]
Ok done ...
I watched this video https://www.youtube.com/watch?v=8lGpZkjnkt4
I had done everything on my side, forked, cloned, created a new branch,
added the new files, committed, and pushed
The only missing piece was done in the web interface ... looks simple, hope
this is what you expected

Best regards
