### ISSUE TITLE
Image format webp not allowed to upload

### ISSUE THREAD

**Issue by ericc-dream** [Moc/cookbook#35]
## Bug Description
I tried to create a new recipe and to upload a picture to illustrate it. 
Image was in webp format and I had an error saying 

>  Unapproved file-type detected. ../../../e107_system/18c158d14e/import/i71869_toasts_au_chevre_avocat_et_tomates_sechees.webp

## How to Reproduce
Admin -> Cookbook -> Add a recipe -> Image : click on the square saying 
> Drop files here to upload

Select a .webp image 

## Expected Behavior
The image to be uploaded. 
The same image in webp is 47Kb , while in png 512Kb 
And in ~/e107_plugins/cookbook/images/ there are some webp images , don't know where they are used however !

### PHP Version
PHP Version 8.2.19

### Client Information
Firefox 126.0.2  on Linux Kubuntu 23.10

**Comment by Moc** [comment]
This is not an issue related to the Cookbook plugin but something in e107 itself (core). 
Check  your filetypes.xml file in the `e107_system/*hash*/` folder you should find it. Add the webp extension there, and you should be able to upload it now.

**Comment by ericc-dream** [comment]
indeed ... modified the filetypes.xml, just added "webp" in the list and worked immediately
